on: [push]
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: 
      name: staging
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'

  deploy-prod:
    runs-on: ubuntu-latest
    environment: 
      name: prod
    needs: [deploy-staging]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'

    
      
